import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import { SignedIn, SignedOut, SignIn, useAuth } from '@clerk/nextjs';
import { useRouter } from 'next/router';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const router = useRouter();
  const { userId } = useAuth();

  function redirecToTodos() {
    if (!sessionStorage.getItem('hasVisited')) {
      router.push('/todos');
      sessionStorage.setItem('hasVisited', 'true');
    }
  }
  if (userId) {
    redirecToTodos();
  }
  return (
    <>
      <Head>
        <title>Sahil'S TodoList</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link
          rel='stylesheet'
          href='https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css'
        />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <section className='section'>
        <div className='container'>
          <h1 className='title'>Sahil's Todolist</h1>
          <p className='subtitle'>
            My first website with <strong>Bulma</strong>!
          </p>
        </div>
      </section>
    </>
  );
}
