import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import { useAuth } from '@clerk/nextjs';
import { SignedIn, SignedOut } from '@clerk/nextjs';
import { useRouter } from 'next/router';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const router = useRouter();
  function redirecToTodos() {
    router.push('/todos');
  }
  return (
    <>
      <Head>
        <title>Sahil'S TodoList</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <SignedIn>{redirecToTodos()}</SignedIn>

      <SignedOut>
        <div>
          <h1>Todolist</h1>
        </div>
      </SignedOut>
    </>
  );
}
